"""Render the weekly digest as HTML and JSON.

The HTML is a single self-contained file (inline CSS, inline favicon, NO web
fonts or external CSS/JS) so it renders identically on the site, in email, and
offline. Visual language: a tech-brief dashboard — mono data layer, a metrics
strip, a week-at-a-glance bar + score histogram, and category lanes with
favicon-style source chips. The shareable card lives at ``digests/<week>.png``
(generated by ``site.build_site``); the head here references it as the og:image
so a pasted digest link unfurls in Teams/Slack.
"""

from __future__ import annotations

import json
from html import escape
from pathlib import Path

from sift.config import DEFAULT_SITE_URL
from sift.fetch import Item
from sift.meta import abs_url, og_tags
from sift.urls import display_domain, safe_href
from sift.weeks import week_range

TAGLINE = "A weekly dispatch of AI signal — curated for one reader"

CATEGORY_LABELS = {
    "models_research": "Models & Research",
    "tooling": "Tooling",
    "infra": "Infra",
    "policy": "Policy",
    "business": "Business",
}

# Self-contained inline favicon (terracotta tile + cream serif "S").
_FAVICON = (
    "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'"
    "%3E%3Crect width='32' height='32' rx='7' fill='%23b4542e'/%3E%3Ctext x='16' y='23.5'"
    " font-family='Georgia,serif' font-size='23' font-weight='bold' fill='%23fdfdfb'"
    " text-anchor='middle'%3ES%3C/text%3E%3C/svg%3E"
)

_STYLE = """
:root { color-scheme: light dark;
  --bg:#f7f3ea; --surface:#fffdf7; --surface-2:#f1ead9; --text:#241f18; --text-2:#473f33;
  --muted:#6c6353; --line:#e5dcc8; --line-2:#d3c8b0; --accent:#b4542e; --badge-ink:#fff;
  --cat-models:#5b54d6; --cat-tooling:#0a7a70; --cat-infra:#b45309; --cat-policy:#be123c;
  --cat-business:#15803d; --live:#15803d; }
/* --cat-tooling darkened from #0d9488 (3.74:1) to clear AA for white badge text. */
@media (prefers-color-scheme: dark) {
  :root { --bg:#1b1410; --surface:#241b14; --surface-2:#2d2218; --text:#efe7d9; --text-2:#d2c6af;
    --muted:#ad9f85; --line:#3b2d20; --line-2:#4c3a29; --accent:#e07a4f; --badge-ink:#1b1410;
    --cat-models:#8b84f0; --cat-tooling:#2dd4bf; --cat-infra:#f59e0b; --cat-policy:#fb7185;
    --cat-business:#4ade80; --live:#4ade80; } }
[data-cat=models_research]{--c:var(--cat-models);} [data-cat=tooling]{--c:var(--cat-tooling);}
[data-cat=infra]{--c:var(--cat-infra);} [data-cat=policy]{--c:var(--cat-policy);}
[data-cat=business]{--c:var(--cat-business);}
* { box-sizing:border-box; }
body { margin:0 auto; max-width:46rem; padding:2.2rem 1.25rem 0; background:var(--bg); color:var(--text);
  font:15px/1.6 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; -webkit-font-smoothing:antialiased; }
.mono { font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace; }
a { color:var(--accent); text-underline-offset:2px; }
.backlink { font:.78rem/1 ui-monospace,Menlo,monospace; margin:0 0 1.4rem; }
.backlink a { color:var(--muted); text-decoration:none; } .backlink a:hover { color:var(--accent); }
header.top { border-bottom:2px solid var(--text); padding-bottom:1rem; margin-bottom:1.3rem; }
.brand { font-family:Georgia,"Times New Roman",serif; font-weight:bold; font-size:2.4rem;
  letter-spacing:-.02em; line-height:1; margin:0; }
.brand .dot { color:var(--accent); }
.issue { font-family:ui-monospace,Menlo,monospace; color:var(--muted); font-size:.82rem;
  letter-spacing:.02em; margin:.5rem 0 0; }
.metrics { display:flex; flex-wrap:wrap; gap:.3rem .7rem; margin:.7rem 0 0; font-family:ui-monospace,Menlo,monospace;
  font-size:.78rem; color:var(--text-2); }
.metrics b { color:var(--accent); font-weight:700; }
.glance { background:var(--surface); border:1px solid var(--line); border-radius:11px;
  padding:1rem 1.1rem; margin:0 0 1.8rem; }
.glance h2 { font:.7rem/1 ui-monospace,Menlo,monospace; letter-spacing:.14em; text-transform:uppercase;
  color:var(--muted); margin:0 0 .7rem; border:0; padding:0; }
.mixbar { display:flex; height:14px; border-radius:7px; overflow:hidden; background:var(--surface-2); }
.mixbar span { display:block; min-width:2px; }
.legend { display:flex; flex-wrap:wrap; gap:.3rem .9rem; margin:.65rem 0 0; font-size:.72rem; color:var(--text-2); }
.legend i { display:inline-block; width:9px; height:9px; border-radius:2px; margin-right:.35rem; vertical-align:middle; }
.spread { margin:.9rem 0 0; }
.spread .bars { display:flex; align-items:flex-end; gap:3px; height:34px; }
.spread .bars i { flex:1; background:var(--c,var(--accent)); border-radius:2px 2px 0 0; min-height:3px; opacity:.85; }
.spread .cap { font:.7rem/1 ui-monospace,Menlo,monospace; color:var(--muted); margin:.4rem 0 0; }
h2.lane { display:flex; align-items:center; gap:.5rem; font:600 .8rem/1 ui-monospace,Menlo,monospace;
  letter-spacing:.1em; text-transform:uppercase; color:var(--text-2); margin:2.4rem 0 .2rem;
  padding:0 0 .4rem; border-bottom:1px solid var(--line); }
h2.lane i { width:10px; height:10px; border-radius:3px; background:var(--c); }
article { display:flex; gap:.85rem; padding:1.15rem 0 1.1rem; border-bottom:1px solid var(--line); border-left:3px solid var(--c);
  padding-left:.9rem; }
.score { flex:0 0 auto; width:2.1rem; height:2.1rem; border-radius:8px; background:var(--c); color:var(--badge-ink);
  font-family:ui-monospace,Menlo,monospace; font-weight:700; font-size:1rem; display:flex; align-items:center;
  justify-content:center; }
.art-body { flex:1; min-width:0; }
.rank { font:.68rem/1 ui-monospace,Menlo,monospace; color:var(--muted); }
article h3 { font-size:1.06rem; line-height:1.3; margin:.15rem 0 .35rem; font-weight:600; }
article h3 a { color:var(--text); text-decoration:none; } article h3 a:hover { color:var(--accent); }
.flag { display:inline-block; font:.6rem/1.3 ui-monospace,Menlo,monospace; text-transform:uppercase;
  letter-spacing:.05em; color:var(--accent); border:1px solid var(--accent); border-radius:4px;
  padding:.12rem .35rem; margin-left:.45rem; white-space:nowrap; vertical-align:middle; }
.summary { margin:.25rem 0; color:var(--text-2); }
.rationale { margin:.35rem 0 .5rem; font-size:.85rem; color:var(--muted); }
.rationale::before { content:"› "; color:var(--accent); }
.chips { display:flex; flex-wrap:wrap; gap:.35rem; }
.chip { display:inline-flex; align-items:center; gap:.35rem; font-size:.74rem; text-decoration:none;
  color:var(--text-2); background:var(--surface-2); border:1px solid var(--line); border-radius:999px;
  padding:.15rem .55rem .15rem .2rem; }
.chip:hover { border-color:var(--accent); color:var(--accent); }
.chip i { width:1.05rem; height:1.05rem; border-radius:50%; display:flex; align-items:center; justify-content:center;
  font:700 .62rem/1 ui-monospace,Menlo,monospace; color:#fff; }
.scanned { margin-top:2.6rem; }
.scanned h2 { font:.7rem/1 ui-monospace,Menlo,monospace; letter-spacing:.12em; text-transform:uppercase;
  color:var(--muted); border-bottom:1px solid var(--line); padding-bottom:.4rem; }
.scanned-list { list-style:none; padding:0; margin:.7rem 0 0; display:flex; flex-wrap:wrap; gap:.4rem .6rem; }
.scanned-list li { font:.74rem/1 ui-monospace,Menlo,monospace; color:var(--muted); background:var(--surface);
  border:1px solid var(--line); border-radius:6px; padding:.28rem .5rem; }
.cnt { color:var(--text); font-weight:700; } .cnt.dead { color:var(--accent); font-style:italic; font-weight:400; }
footer { margin:3rem 0 2.5rem; padding-top:1.1rem; border-top:1px solid var(--line); color:var(--muted);
  font-size:.8rem; font-style:italic; }
:focus-visible { outline:2px solid var(--accent); outline-offset:2px; border-radius:4px; }
@media (max-width:480px){ .brand{font-size:2rem;} article{gap:.6rem;} .score{width:1.9rem;height:1.9rem;} }
@media (prefers-reduced-motion:reduce){ *{transition:none!important;} }
"""

_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sift — Week {week}</title>
<meta name="description" content="{desc}">
<link rel="icon" href="{favicon}" type="image/svg+xml">
{og}
<style>{style}</style>
</head>
<body>
<p class="backlink"><a href="index.html">&larr; all issues</a> &middot; <a href="../index.html">about Sift</a></p>
<header class="top">
<h1 class="brand">Sift<span class="dot">.</span></h1>
<p class="issue">Week {week}{range_sep}{range}</p>
<p class="metrics">{metrics}</p>
</header>
{glance}
{sections}
{scanned}
<footer>Curated weekly from your feeds — one Claude call, everything else local and free.</footer>
</body>
</html>
"""


def build_digest(
    week: str,
    stories: list[dict],
    clusters: list[list[Item]],
    feed_results: list | None = None,
    cost_usd: float | None = None,
) -> dict:
    """Join ranked stories back to their source items; sort by score.

    feed_results (fetch.FeedResult) records which sources were scanned this run.
    cost_usd, when provided, is recorded so the digest can show the run cost.
    """
    enriched = []
    for story in sorted(stories, key=lambda s: s["score"], reverse=True):
        links = [
            {"url": item.url, "source": item.source}
            for cid in story["cluster_ids"]
            for item in clusters[cid]
        ]
        enriched.append({**story, "links": links})
    digest: dict = {"week": week, "stories": enriched}
    if cost_usd is not None:
        digest["cost_usd"] = round(float(cost_usd), 4)
    if feed_results is not None:
        digest["sources_scanned"] = [
            {"name": r.name, "count": r.count, "ok": r.ok} for r in feed_results
        ]
    return digest


def render_json(digest: dict, path: Path) -> None:
    path.write_text(json.dumps(digest, indent=2) + "\n", encoding="utf-8")


def render_html(
    digest: dict,
    path: Path,
    *,
    site_url: str = DEFAULT_SITE_URL,
    cost_usd: float | None = None,
    og_image: str | None = None,
) -> None:
    week = digest["week"]
    stories = digest["stories"]
    # An explicit cost_usd (e.g. the accumulated same-week total from history)
    # wins over a stale value baked into the stored digest JSON.
    cost = cost_usd if cost_usd is not None else digest.get("cost_usd")
    sources = digest.get("sources_scanned")
    # Default og:image is this week's cover card; callers pass og_image to fall
    # back to the static site card when the per-issue card could not be written.
    image = og_image or abs_url(site_url, f"digests/{week}.png")

    desc = stories[0]["title"] if stories else TAGLINE
    page = _PAGE.format(
        week=escape(week),
        desc=escape(desc, quote=True),
        favicon=_FAVICON,
        og=og_tags(
            title=f"Sift — Week {week}",
            description=desc,
            url=abs_url(site_url, f"digests/{week}.html"),
            image=image,
            image_alt=f"Sift digest cover — Week {week}",
        ),
        style=_STYLE,
        range_sep=" &middot; " if week_range(week) else "",
        range=escape(week_range(week)),
        metrics=_metrics_html(len(stories), sources, cost),
        glance=_glance_html(stories),
        sections=_sections_html(stories),
        scanned=_sources_scanned_html(digest),
    )
    path.write_text(page, encoding="utf-8")


def _metrics_html(count: int, sources: list | None, cost: float | None) -> str:
    bits = [f"<b>{count}</b> stories"]
    if sources:
        live = sum(1 for s in sources if s["ok"])
        bits.append(f"<b>{live}/{len(sources)}</b> feeds live")
    if cost:
        bits.append(f"<b>${cost:.2f}</b> run")
    return " &middot; ".join(bits)


def _glance_html(stories: list[dict]) -> str:
    if not stories:
        return ""
    counts: dict[str, int] = {}
    for s in stories:
        counts[s["category"]] = counts.get(s["category"], 0) + 1
    total = sum(counts.values()) or 1
    segs, legend = [], []
    for cat, label in CATEGORY_LABELS.items():
        n = counts.get(cat, 0)
        if not n:
            continue
        pct = round(100 * n / total, 2)
        segs.append(
            f'<span data-cat="{cat}" style="width:{pct}%;background:var(--c)" '
            f'title="{escape(label)}: {n}"></span>'
        )
        legend.append(
            f'<span data-cat="{cat}"><i style="background:var(--c)"></i>{escape(label)} {n}</span>'
        )
    scores = [int(s["score"]) for s in stories]
    bars = "".join(
        f'<i data-cat="{escape(s["category"])}" style="height:{int(s["score"]) * 10}%"></i>'
        for s in stories
    )
    cap = f"hi {max(scores)} &middot; lo {min(scores)} &middot; avg {sum(scores) / len(scores):.1f}"
    return (
        '<section class="glance" aria-label="Week at a glance">\n'
        "<h2>Week at a glance</h2>\n"
        f'<div class="mixbar" role="img" aria-label="Category mix">{"".join(segs)}</div>\n'
        f'<div class="legend">{"".join(legend)}</div>\n'
        '<div class="spread">'
        f'<div class="bars" role="img" aria-label="Score spread">{bars}</div>'
        f'<p class="cap mono">{cap}</p></div>\n'
        "</section>\n"
    )


def _sections_html(stories: list[dict]) -> str:
    ranked = {id(s): i + 1 for i, s in enumerate(stories)}  # global importance rank
    sections = []
    for category, label in CATEGORY_LABELS.items():
        in_cat = [s for s in stories if s["category"] == category]
        if not in_cat:
            continue
        articles = "\n".join(_article(s, ranked[id(s)]) for s in in_cat)
        sections.append(
            f'<h2 class="lane" data-cat="{category}"><i></i>{escape(label)}</h2>\n{articles}'
        )
    return "\n".join(sections)


def _sources_scanned_html(digest: dict) -> str:
    sources = digest.get("sources_scanned")
    if not sources:
        return ""
    items = "".join(
        f"<li>{escape(s['name'])} "
        + (
            f'<span class="cnt">{s["count"]}</span>'
            if s["ok"]
            else '<span class="cnt dead">dead</span>'
        )
        + "</li>"
        for s in sources
    )
    live = sum(1 for s in sources if s["ok"])
    return (
        '<section class="scanned">\n'
        f"<h2>Sources scanned &middot; {live}/{len(sources)} live</h2>\n"
        f'<ul class="scanned-list">{items}</ul>\n'
        "</section>"
    )


def _article(story: dict, rank: int) -> str:
    primary_url = story["links"][0]["url"] if story["links"] else "#"
    flag = '<span class="flag">needs verification</span>' if story["needs_verification"] else ""
    chips = "".join(_source_chip(link) for link in story["links"])
    return (
        f'<article data-cat="{escape(story["category"])}">\n'
        f'<span class="score" title="importance {story["score"]}/10">{story["score"]}</span>\n'
        '<div class="art-body">\n'
        f'<span class="rank mono">#{rank}</span>\n'
        f'<h3><a href="{escape(safe_href(primary_url))}">{escape(story["title"])}</a>{flag}</h3>\n'
        f'<p class="summary">{escape(story["summary"])}</p>\n'
        f'<p class="rationale">{escape(story["rationale"])}</p>\n'
        f'<div class="chips">{chips}</div>\n'
        "</div>\n"
        "</article>"
    )


def _source_chip(link: dict) -> str:
    # Raw domain (or feed-name fallback); escaped once at each sink below.
    domain = display_domain(link["url"]) or link["source"]
    initial = escape((domain[:1] or "?").upper())
    hue = sum(ord(c) for c in domain) % 360  # stable monogram tint
    # Lightness 33% keeps the white monogram letter ≥4.5:1 across all hues.
    return (
        f'<a class="chip" href="{escape(safe_href(link["url"]))}">'
        f'<i style="background:hsl({hue} 50% 33%)">{initial}</i>'
        f'<span>{escape(domain)}</span></a>'
    )
