"""Render the weekly digest as HTML and JSON.

The HTML is a single self-contained file (inline CSS, inline favicon, NO web
fonts or external CSS/JS) so it renders identically on the site, in email, and
offline. Visual language: a tech-brief dashboard — mono data layer, a metrics
strip, a week-at-a-glance bar + score histogram, and category lanes with
favicon-style source chips. The shareable card lives at ``digests/<week>.png``
(generated by ``site.build_site``); the head here references it as the og:image
so a pasted digest link unfurls in Teams/Slack.
"""

from __future__ import annotations

import json
from html import escape
from urllib.parse import quote
from pathlib import Path

from sift import iso, theme
from sift.config import DEFAULT_SITE_URL
from sift.fetch import Item
from sift.meta import abs_url, og_tags
from sift.urls import display_domain, safe_href
from sift.weeks import week_range

TAGLINE = "A weekly dispatch of AI signal — curated for one reader"

CATEGORY_LABELS = theme.CATEGORY_LABELS

# The digest is self-contained, so it carries its own copy of the palette rather
# than linking the site stylesheet.
_PALETTE = theme.palette()

# The digest carries no visible theme control — it is also read in email, where
# a dead set of buttons would be worse than none. It does honour a choice made
# on the site, so clicking through from the archive keeps the reader's theme.
# The whole thing is inline and never touches the network; an email client that
# strips scripts simply falls back to the system preference.
_THEME_BOOTSTRAP = """<script>
(function () {
  try {
    var t = localStorage.getItem('sift-theme');
    if (t === 'light' || t === 'dark') document.documentElement.dataset.theme = t;
  } catch (e) {}
})();
</script>"""


def _favicon_data_uri() -> str:
    """The mark as an inline data: URI — the digest may be read offline or in an
    email client, so it must not reference an external icon."""
    svg = iso.favicon(_PALETTE)
    return "data:image/svg+xml," + quote(svg, safe="")


def _style() -> str:
    """The digest's inline stylesheet. Dark-only and system-font-only: this file
    has to render the same in a browser, in an email client and offline, so it
    links nothing and assumes no web font."""
    pal = _PALETTE
    fonts = f"""  --surface: rgba(var(--glass-rgb), .05);
  --surface-2: rgba(var(--glass-rgb), .09);
  --line: rgba(var(--glass-rgb), .11);
  --line-2: rgba(var(--glass-rgb), .20);
  --display: {theme.FONT_DISPLAY_FALLBACK};
  --body: {theme.FONT_BODY_FALLBACK};
  --mono: {theme.FONT_MONO_FALLBACK};"""
    return f"""
{theme.theme_blocks(pal, extra=fonts)}
{theme.category_selectors(pal)}
* {{ box-sizing:border-box; }}
body {{ margin:0 auto; max-width:52rem; padding:2.4rem 1.25rem 0; background:var(--bg);
  color:var(--text); font:16px/1.6 var(--body); -webkit-font-smoothing:antialiased; }}
a {{ color:var(--accent); text-underline-offset:2px; }}
a:hover {{ color:var(--accent-hi); }}
h1, h2, h3 {{ font-family:var(--display); margin:0; }}
p {{ margin:0; }}
.mono {{ font-family:var(--mono); }}
.backlink {{ font:.78rem/1 var(--mono); margin:0 0 1.6rem; }}
.backlink a {{ color:var(--muted); text-decoration:none; }}
.backlink a:hover {{ color:var(--accent); }}
header.top {{ display:flex; align-items:flex-start; justify-content:space-between; gap:1.5rem;
  border-bottom:1px solid var(--line); padding-bottom:1.2rem; margin-bottom:1.6rem; flex-wrap:wrap; }}
.brand {{ font-family:var(--display); font-weight:bold; font-size:2.6rem; letter-spacing:-.03em;
  line-height:1; margin:0; }}
.brand .dot {{ color:var(--accent); }}
.top-mark svg {{ width:3.4rem; height:3.4rem; }}
.issue {{ font-family:var(--mono); color:var(--muted); font-size:.82rem; letter-spacing:.04em;
  margin:.6rem 0 0; }}
.metrics {{ display:flex; flex-wrap:wrap; gap:.35rem .9rem; margin:.8rem 0 0;
  font-family:var(--mono); font-size:.8rem; color:var(--text-2); }}
.metrics b {{ color:var(--accent-hi); font-weight:700; }}
.glance {{ background:var(--surface); border:1px solid var(--line); border-radius:14px;
  padding:1.2rem 1.3rem; margin:0 0 2rem; }}
.glance h2 {{ font:.7rem/1 var(--mono); letter-spacing:.16em; text-transform:uppercase;
  color:var(--muted); margin:0 0 .9rem; }}
.mixbar {{ display:flex; height:16px; border-radius:8px; overflow:hidden;
  background:var(--surface-2); gap:2px; }}
.mixbar span {{ display:block; min-width:2px; }}
.legend {{ display:flex; flex-wrap:wrap; gap:.5rem 1.3rem; margin:.9rem 0 0; font-size:.85rem;
  color:var(--text-2); }}
.legend span {{ display:inline-flex; align-items:center; gap:.45rem; }}
.legend svg {{ width:1.4rem; height:1.4rem; flex:0 0 1.4rem; }}
.legend b {{ font-family:var(--mono); font-weight:500; color:var(--text); font-size:.8rem; }}
.spread {{ margin:1.1rem 0 0; }}
.spread .bars {{ display:flex; align-items:flex-end; gap:4px; height:44px; }}
.spread .bars i {{ flex:1; background:var(--c,var(--accent)); border-radius:3px 3px 0 0;
  min-height:4px; opacity:.9; }}
.spread .cap {{ font:.72rem/1 var(--mono); color:var(--muted); margin:.6rem 0 0; }}
h2.lane {{ display:flex; align-items:center; gap:.6rem; font-size:1.25rem; font-weight:600;
  letter-spacing:-.02em; color:var(--text); margin:2.8rem 0 .2rem; padding:0 0 .7rem;
  border-bottom:1px solid var(--line); }}
h2.lane svg {{ width:1.7rem; height:1.7rem; flex:0 0 1.7rem; }}
h2.lane .cnt {{ margin-left:auto; font-family:var(--mono); font-size:.72rem; letter-spacing:.1em;
  color:var(--muted); font-weight:400; }}
article {{ display:flex; gap:1.1rem; padding:1.4rem 0; border-bottom:1px solid var(--line); }}
.score {{ flex:0 0 auto; width:3rem; height:3rem; border-radius:12px; color:var(--accent-ink);
  font-family:var(--display); font-weight:700; font-size:1.3rem; display:flex;
  align-items:center; justify-content:center;
  background:linear-gradient(160deg, var(--c) 0%, var(--c) 45%, rgba(0,0,0,.35) 100%);
  box-shadow:inset 0 1px 0 rgba(255,255,255,.35), inset 0 -2px 0 rgba(0,0,0,.25); }}
.art-body {{ flex:1; min-width:0; }}
.rank {{ font:.7rem/1 var(--mono); letter-spacing:.12em; color:var(--muted); }}
article h3 {{ font-size:1.2rem; line-height:1.3; margin:.3rem 0 .5rem; font-weight:600;
  letter-spacing:-.015em; }}
article h3 a {{ color:var(--text); text-decoration:none; }}
article h3 a:hover {{ color:var(--accent-hi); }}
.flag {{ display:inline-block; font:.6rem/1.3 var(--mono); text-transform:uppercase;
  letter-spacing:.08em; color:var(--accent-hi); border:1px solid var(--accent);
  border-radius:5px; padding:.15rem .4rem; margin-left:.5rem; white-space:nowrap;
  vertical-align:middle; }}
.summary {{ margin:.3rem 0; color:var(--text-2); }}
.rationale {{ margin:.5rem 0 .7rem; font-size:.88rem; color:var(--muted); }}
.rationale::before {{ content:"› "; color:var(--accent); }}
.chips {{ display:flex; flex-wrap:wrap; gap:.4rem; }}
.chip {{ display:inline-flex; align-items:center; gap:.4rem; font-size:.78rem;
  text-decoration:none; color:var(--text-2); background:var(--surface);
  border:1px solid var(--line); border-radius:999px; padding:.2rem .7rem .2rem .25rem; }}
.chip:hover {{ border-color:var(--accent); color:var(--accent-hi); }}
.chip i {{ width:1.15rem; height:1.15rem; border-radius:50%; display:flex; align-items:center;
  justify-content:center; font:700 .65rem/1 var(--mono); color:#fff; }}
.chip .n {{ color:var(--muted); }}
.scanned {{ margin-top:3rem; background:var(--surface); border:1px solid var(--line);
  border-radius:14px; padding:1.2rem 1.3rem; }}
.scanned h2 {{ font:.7rem/1 var(--mono); letter-spacing:.16em; text-transform:uppercase;
  color:var(--muted); margin:0; }}
.scanned-list {{ list-style:none; padding:0; margin:1rem 0 0; display:flex; flex-wrap:wrap;
  gap:.45rem; }}
.scanned-list li {{ font:.76rem/1 var(--mono); color:var(--muted); background:var(--bg-2);
  border:1px solid var(--line); border-radius:8px; padding:.35rem .6rem; }}
.cnt {{ color:var(--text); font-weight:700; }}
.cnt.dead {{ color:var(--accent-hi); font-style:italic; font-weight:400; }}
footer {{ margin:3.2rem 0 2.6rem; padding-top:1.3rem; border-top:1px solid var(--line);
  color:var(--muted); font-size:.85rem; }}
:focus-visible {{ outline:2px solid var(--accent); outline-offset:2px; border-radius:4px; }}
@media (max-width:480px) {{
  .brand {{ font-size:2.1rem; }} article {{ gap:.75rem; }}
  .score {{ width:2.5rem; height:2.5rem; font-size:1.1rem; }}
  .top-mark {{ display:none; }}
  /* Source chips are tapped rather than clicked here, so they take a full
     touch target on phones and stay compact on the desktop. */
  .chip {{ min-height:44px; padding:.2rem .9rem .2rem .3rem; }}
  .backlink a {{ display:inline-flex; align-items:center; min-height:44px; }}
}}
@media (prefers-reduced-motion:reduce) {{ * {{ transition:none!important; animation:none!important; }} }}
"""


_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Sift — Week {week}</title>
<meta name="description" content="{desc}">
<link rel="icon" href="{favicon}" type="image/svg+xml">
{og}
{theme_bootstrap}
<style>{style}</style>
</head>
<body>
<p class="backlink"><a href="index.html">&larr; all issues</a> &middot; <a href="../index.html">about Sift</a></p>
<header class="top">
<div>
<h1 class="brand">Sift<span class="dot">.</span></h1>
<p class="issue">Week {week}{range_sep}{range}</p>
<p class="metrics">{metrics}</p>
</div>
<div class="top-mark" aria-hidden="true">{mark}</div>
</header>
{glance}
{sections}
{scanned}
<footer>Curated weekly from your feeds — one Claude call, everything else local and free.</footer>
</body>
</html>
"""


def build_digest(
    week: str,
    stories: list[dict],
    clusters: list[list[Item]],
    feed_results: list | None = None,
    cost_usd: float | None = None,
) -> dict:
    """Join ranked stories back to their source items; sort by score.

    feed_results (fetch.FeedResult) records which sources were scanned this run.
    cost_usd, when provided, is recorded so the digest can show the run cost.
    """
    enriched = []
    for story in sorted(stories, key=lambda s: s["score"], reverse=True):
        links = [
            {"url": item.url, "source": item.source}
            for cid in story["cluster_ids"]
            for item in clusters[cid]
        ]
        enriched.append({**story, "links": links})
    digest: dict = {"week": week, "stories": enriched}
    if cost_usd is not None:
        digest["cost_usd"] = round(float(cost_usd), 4)
    if feed_results is not None:
        digest["sources_scanned"] = [
            {"name": r.name, "count": r.count, "ok": r.ok} for r in feed_results
        ]
    return digest


def render_json(digest: dict, path: Path) -> None:
    path.write_text(json.dumps(digest, indent=2) + "\n", encoding="utf-8")


def render_html(
    digest: dict,
    path: Path,
    *,
    site_url: str = DEFAULT_SITE_URL,
    cost_usd: float | None = None,
    og_image: str | None = None,
) -> None:
    week = digest["week"]
    stories = digest["stories"]
    # An explicit cost_usd (e.g. the accumulated same-week total from history)
    # wins over a stale value baked into the stored digest JSON.
    cost = cost_usd if cost_usd is not None else digest.get("cost_usd")
    sources = digest.get("sources_scanned")
    # Default og:image is this week's cover card; callers pass og_image to fall
    # back to the static site card when the per-issue card could not be written.
    image = og_image or abs_url(site_url, f"digests/{week}.png")

    desc = stories[0]["title"] if stories else TAGLINE
    page = _PAGE.format(
        week=escape(week),
        desc=escape(desc, quote=True),
        favicon=_favicon_data_uri(),
        og=og_tags(
            title=f"Sift — Week {week}",
            description=desc,
            url=abs_url(site_url, f"digests/{week}.html"),
            image=image,
            image_alt=f"Sift digest cover — Week {week}",
        ),
        style=_style(),
        theme_bootstrap=_THEME_BOOTSTRAP,
        mark=iso.mark(_PALETTE, size=54),
        range_sep=" &middot; " if week_range(week) else "",
        range=escape(week_range(week)),
        metrics=_metrics_html(len(stories), sources, cost),
        glance=_glance_html(stories),
        sections=_sections_html(stories),
        scanned=_sources_scanned_html(digest),
    )
    path.write_text(page, encoding="utf-8")


def _metrics_html(count: int, sources: list | None, cost: float | None) -> str:
    bits = [f"<b>{count}</b> stories"]
    if sources:
        live = sum(1 for s in sources if s["ok"])
        bits.append(f"<b>{live}/{len(sources)}</b> feeds live")
    if cost:
        bits.append(f"<b>${cost:.2f}</b> run")
    return " &middot; ".join(bits)


def _glance_html(stories: list[dict]) -> str:
    if not stories:
        return ""
    counts: dict[str, int] = {}
    for s in stories:
        counts[s["category"]] = counts.get(s["category"], 0) + 1
    total = sum(counts.values()) or 1
    segs, legend = [], []
    for cat, label in CATEGORY_LABELS.items():
        n = counts.get(cat, 0)
        if not n:
            continue
        pct = round(100 * n / total, 2)
        segs.append(
            f'<span data-cat="{cat}" style="width:{pct}%;background:var(--c)" '
            f'title="{escape(label)}: {n}"></span>'
        )
        legend.append(
            f'<span data-cat="{cat}">{iso.category_glyph(cat, _PALETTE)}'
            f"{escape(label)} <b>{n}</b></span>"
        )
    scores = [int(s["score"]) for s in stories]
    bars = "".join(
        f'<i data-cat="{escape(s["category"])}" style="height:{int(s["score"]) * 10}%"></i>'
        for s in stories
    )
    cap = f"hi {max(scores)} &middot; lo {min(scores)} &middot; avg {sum(scores) / len(scores):.1f}"
    return (
        '<section class="glance" aria-label="Week at a glance">\n'
        "<h2>Week at a glance</h2>\n"
        f'<div class="mixbar" role="img" aria-label="Category mix">{"".join(segs)}</div>\n'
        f'<div class="legend">{"".join(legend)}</div>\n'
        '<div class="spread">'
        f'<div class="bars" role="img" aria-label="Score spread">{bars}</div>'
        f'<p class="cap mono">{cap}</p></div>\n'
        "</section>\n"
    )


def _sections_html(stories: list[dict]) -> str:
    ranked = {id(s): i + 1 for i, s in enumerate(stories)}  # global importance rank
    sections = []
    for category, label in CATEGORY_LABELS.items():
        in_cat = [s for s in stories if s["category"] == category]
        if not in_cat:
            continue
        articles = "\n".join(_article(s, ranked[id(s)]) for s in in_cat)
        plural = "story" if len(in_cat) == 1 else "stories"
        sections.append(
            f'<h2 class="lane" data-cat="{category}">'
            f"{iso.category_glyph(category, _PALETTE)}{escape(label)}"
            f'<span class="cnt">{len(in_cat)} {plural}</span></h2>\n{articles}'
        )
    return "\n".join(sections)


def _sources_scanned_html(digest: dict) -> str:
    sources = digest.get("sources_scanned")
    if not sources:
        return ""
    items = "".join(
        f"<li>{escape(s['name'])} "
        + (
            f'<span class="cnt">{s["count"]}</span>'
            if s["ok"]
            else '<span class="cnt dead">dead</span>'
        )
        + "</li>"
        for s in sources
    )
    live = sum(1 for s in sources if s["ok"])
    return (
        '<section class="scanned">\n'
        f"<h2>Sources scanned &middot; {live}/{len(sources)} live</h2>\n"
        f'<ul class="scanned-list">{items}</ul>\n'
        "</section>"
    )


def _article(story: dict, rank: int) -> str:
    primary_url = story["links"][0]["url"] if story["links"] else "#"
    flag = '<span class="flag">needs verification</span>' if story["needs_verification"] else ""
    chips = _source_chips(story["links"])
    return (
        f'<article data-cat="{escape(story["category"])}">\n'
        f'<span class="score" title="importance {story["score"]}/10">{story["score"]}</span>\n'
        '<div class="art-body">\n'
        f'<span class="rank mono">#{rank}</span>\n'
        f'<h3><a href="{escape(safe_href(primary_url))}">{escape(story["title"])}</a>{flag}</h3>\n'
        f'<p class="summary">{escape(story["summary"])}</p>\n'
        f'<p class="rationale">{escape(story["rationale"])}</p>\n'
        f'<div class="chips">{chips}</div>\n'
        "</div>\n"
        "</article>"
    )


def _source_chips(links: list[dict]) -> str:
    """One chip per distinct source domain. A story that cites the same domain
    several times (a thread of posts, say) gets a single chip with a count,
    rather than the same chip repeated."""
    seen: dict[str, dict] = {}
    counts: dict[str, int] = {}
    for link in links:
        domain = display_domain(link["url"]) or link["source"]
        seen.setdefault(domain, link)
        counts[domain] = counts.get(domain, 0) + 1
    return "".join(_source_chip(link, counts[domain]) for domain, link in seen.items())


def _source_chip(link: dict, count: int = 1) -> str:
    # Raw domain (or feed-name fallback); escaped once at each sink below.
    domain = display_domain(link["url"]) or link["source"]
    initial = escape((domain[:1] or "?").upper())
    hue = sum(ord(c) for c in domain) % 360  # stable monogram tint
    # Lightness 33% keeps the white monogram letter ≥4.5:1 across all hues.
    tally = f' <span class="n">&times;{count}</span>' if count > 1 else ""
    return (
        f'<a class="chip" href="{escape(safe_href(link["url"]))}">'
        f'<i style="background:hsl({hue} 50% 33%)">{initial}</i>'
        f"<span>{escape(domain)}{tally}</span></a>"
    )
